# settings.yaml

# Path to file with files information
file_info_path: "filelist.json"

# Maximum file size to attempt to upload
# max_file_size: 10485760  # Maximum file size in bytes (10MB in this example)
max_file_size: 10000000000

# Bee API endpoint
bee_api_endpoint: ""

# Stamp ID
stamp_id: ""

# Upload selection
upload_filter: "pending" # "all" or "pending"

# Deferred upload (true or false)
deferred_upload: false

# Path to download location
download_location_path: "./downloads"

## HTML generation settings

# Page title
page_title: "My Swarm Files"

# Page footer to include (optional)
page_footer: "footer.txt"

# Page styles to include (optional)
page_css_styles: "styles.css"

# Swarm gateway to use (full URL, reference hash concatenated)
swarm_gateway: "https://gateway.fairdatasociety.org/bzz/"

# Explainer text to put before the table of files
placeholder_text: "Clicking on the links will use a gateway to access the file. Larger files might not be accesible through the gateway. Try using local Bee node by installing Bee desktop via <a href="https://desktop.ethswarm.org">https://desktop.ethswarm.org</a> " 
